if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("BlueBar",["csx","CSS","DOMQuery","Style","ge"],(function(a,b,c,d,e,f,g,h){var i=document,j={};function k(a){return d("DOMQuery").scry(i,a)[0]}function l(a,b){return j[a]?j[a]:j[a]=k(b)}function a(){i=c("ge")("blueBarDOMInspector")||document,j={}}function b(){var a=n();return!a?!1:d("CSS").matchesSelector(a,"._5rmj")||c("Style").isFixed(a)}function m(){return l("bar","div._1s4v")}function e(){return l("navRoot","div._cx4")||m()}function n(){return l("maybeFixedRoot","div._26aw")}function f(){return l("maybeFixedRootLoggedOut","div._1pmx")}function h(){return l("maybeFixedRootLogin","div._53jh")}a();g.hasFixedBlueBar=b;g.getBar=m;g.getNavRoot=e;g.getMaybeFixedRoot=n;g.getLoggedOutRoot=f;g.getNewLoggedOutRoot=h}),98);
__d("React",["cr:1108857","cr:1294158","gkx"],(function(a,b,c,d,e,f){var g=b("cr:1294158").useSyncExternalStore;function a(a,b,c){return g(b,c)}b("gkx")("4166")&&(b("cr:1294158").useMutableSource=a,b("cr:1294158").unstable_useMutableSource=a);e.exports=b("cr:1294158")}),null);
__d("useLayoutEffect_SAFE_FOR_SSR",["ExecutionEnvironment","react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.useEffect;c=a.useLayoutEffect;e=d("ExecutionEnvironment").canUseDOM?c:b;f=e;g["default"]=f}),98);
__d("warning",["WebDriverConfig","cr:1105154","cr:11202","cr:2682"],(function(a,b,c,d,e,f,g){a=b("cr:2682");c=a;g["default"]=c}),98);
__d("getReferrerURI",["ErrorGuard","URI","isFacebookURI"],(function(a,b,c,d,e,f,g){"use strict";function b(){if(a.PageTransitions&&a.PageTransitions.isInitialized())return a.PageTransitions.getReferrerURI();else{var b=c("ErrorGuard").applyWithGuard(function(a){return c("URI").tryParseURI(a)},null,[document.referrer]);return b&&c("isFacebookURI")(b)?b:null}}g["default"]=b}),98);
__d("ViewportBounds",["Arbiter","ArbiterMixin","BlueBar","ExecutionEnvironment","PageEvents","Vector","emptyFunction","removeFromArray"],(function(a,b,c,d,e,f){var g={top:[],right:[],bottom:[],left:[]};function a(a){return function(){return g[a].reduce(function(a,b){return Math.max(a,b.getSize())},0)}}function c(a,b){return function(c){return new h(a,c,b)}}var h=function(){"use strict";function a(a,c,d){d===void 0&&(d=!1),this.getSide=b("emptyFunction").thatReturns(a),this.getSize=function(){return typeof c==="function"?c():c},this.isPersistent=b("emptyFunction").thatReturns(d),g[a].push(this),i.inform("change")}var c=a.prototype;c.remove=function(){b("removeFromArray")(g[this.getSide()],this),i.inform("change")};return a}();b("Arbiter").subscribe(b("PageEvents").AJAXPIPE_ONUNLOAD,function(){["top","right","bottom","left"].forEach(function(a){a=g[a];for(var b=a.length-1;b>=0;b--){var c=a[b];c.isPersistent()||c.remove()}})});var i=babelHelpers["extends"]({},b("ArbiterMixin"),{getTop:a("top"),getRight:a("right"),getBottom:a("bottom"),getLeft:a("left"),getElementPosition:function(a){a=b("Vector").getElementPosition(a);a.y-=i.getTop();return a},addTop:c("top"),addRight:c("right"),addBottom:c("bottom"),addLeft:c("left"),addPersistentTop:c("top",!0),addPersistentRight:c("right",!0),addPersistentBottom:c("bottom",!0),addPersistentLeft:c("left",!0)});i.addPersistentTop(function(){if(b("ExecutionEnvironment").canUseDOM&&b("BlueBar").hasFixedBlueBar()){var a=b("BlueBar").getMaybeFixedRoot();return a?a.offsetHeight:0}return 0});e.exports=i}),null);
__d("isAsyncScrollQuery",["UserAgent"],(function(a,b,c,d,e,f,g){var h=null;function a(){h===null&&(h=c("UserAgent").isPlatform("Mac OS X >= 10.8")&&c("UserAgent").isBrowser("Safari >= 6.0"));return h}g["default"]=a}),98);
__d("setInterval",["cr:896461"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:896461")}),98);
__d("ActorURIConfig",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({PARAMETER_ACTOR:"av",ENCRYPTED_PARAMETER_ACTOR:"eav"})}),null);
__d("ActorURI",["ActorURIConfig","URI"],(function(a,b,c,d,e,f,g){function a(a,b){return new(c("URI"))(a).addQueryData(c("ActorURIConfig").PARAMETER_ACTOR,b)}g.create=a;g.PARAMETER_ACTOR=c("ActorURIConfig").PARAMETER_ACTOR}),98);
__d("scheduler",["SchedulerFb-Internals_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";e.exports=b("SchedulerFb-Internals_DO_NOT_USE")}),null);
__d("cancelAnimationFramePolyfill",[],(function(a,b,c,d,e,f){b=a.__fbNativeCancelAnimationFrame||a.cancelAnimationFrame||a.webkitCancelAnimationFrame||a.mozCancelAnimationFrame||a.oCancelAnimationFrame||a.msCancelAnimationFrame||a.clearTimeout;c=b;f["default"]=c}),66);
__d("cancelAnimationFrame",["cancelAnimationFramePolyfill"],(function(a,b,c,d,e,f,g){function a(a){c("cancelAnimationFramePolyfill")(a)}g["default"]=a}),98);
__d("setIntervalBlue",["TimerStorage","setIntervalAcrossTransitions"],(function(a,b,c,d,e,f,g){function a(a,b){for(var d=arguments.length,e=new Array(d>2?d-2:0),f=2;f<d;f++)e[f-2]=arguments[f];var g=c("setIntervalAcrossTransitions").apply(void 0,[a,b].concat(e));c("TimerStorage").set(c("TimerStorage").INTERVAL,g);return g}g["default"]=a}),98);
__d("ReactCurrentOwner",[],(function(a,b,c,d,e,f){"use strict";a={current:null};e.exports=a}),null);
__d("ReactDOMLegacy_DEPRECATED",["cr:1108857","cr:1294246"],(function(a,b,c,d,e,f,g){g.createPortal=b("cr:1294246").createPortal,g.findDOMNode=b("cr:1294246").findDOMNode,g.flushSync=b("cr:1294246").flushSync,g.hydrate=b("cr:1294246").hydrate,g.render=b("cr:1294246").render,g.unmountComponentAtNode=b("cr:1294246").unmountComponentAtNode,g.unstable_batchedUpdates=b("cr:1294246").unstable_batchedUpdates,g.unstable_renderSubtreeIntoContainer=b("cr:1294246").unstable_renderSubtreeIntoContainer,g.version=b("cr:1294246").version,g.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED=b("cr:1294246").__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED}),98);
__d("ReactDOM",["ReactDOMLegacy_DEPRECATED"],(function(a,b,c,d,e,f){Object.keys(importNamespace("ReactDOMLegacy_DEPRECATED")).forEach(function(a){if(a==="default"||a==="__esModule")return;f[a]=importNamespace("ReactDOMLegacy_DEPRECATED")[a]})}),null);
__d("SubscriptionsHandler",["invariant"],(function(a,b,c,d,e,f,g,h){"use strict";function i(a){return a.remove||a.reset||a.unsubscribe||a.cancel||a.dispose}function j(a){i(a).call(a)}a=function(){function a(){this.$1=[]}var b=a.prototype;b.addSubscriptions=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];b.every(i)||h(0,3659);this.$1!=null?this.$1=this.$1.concat(b):b.forEach(j)};b.engage=function(){this.$1==null&&(this.$1=[])};b.release=function(){this.$1!=null&&(this.$1.forEach(j),this.$1=null)};b.releaseOne=function(a){var b=this.$1;if(b==null)return;var c=b.indexOf(a);c!==-1&&(j(a),b.splice(c,1),b.length===0&&(this.$1=null))};return a}();g["default"]=a}),98);